import React, { useMemo, useRef, useState } from "react";
import { Download, Copy, FileText, ImagePlus, Palette, Plus, Save, Trash2, Type, Upload, Wand2, GripVertical } from "lucide-react";
import "./CompanyDocuments.css";

const KEY="stylz_ims_company_documents";
const COMPANY_KEY="stylz_ims_company_profile";
const defaults={name:"STYLZ DIGITAL SOLUTIONS",tagline:"Creative Printing, Branding & Digital Solutions",registration:"Reg No. 2023/916461/07 · Zimbabwe & South Africa",address:"Randfontein, Gauteng, South Africa",phone:"",email:"info@stylzdigital.co.za",website:"stylzdigital.co.za",services:"Large-format printing, digital printing, graphic design, websites, online applications and branding.",primary:"#174ea6",secondary:"#e31b23",font:"Arial"};
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||"null")||f}catch{return f}};
const uid=()=>Date.now()+Math.random();
const blocksFor=(type)=>type==="profile"?[{id:uid(),type:"hero",title:"COMPANY PROFILE",text:"Professional solutions for modern businesses."},{id:uid(),type:"text",title:"About Us",text:"Tell customers who you are, what you do and why they should work with you."},{id:uid(),type:"columns",title:"Mission & Vision",text:"Our mission|Our vision"},{id:uid(),type:"services",title:"Our Services",text:"Printing and branding|Graphic design|Websites|Business solutions"},{id:uid(),type:"values",title:"Our Values",text:"Quality|Reliability|Creativity|Professionalism"}]:[{id:uid(),type:"letterHeader",title:"Business Letterhead",text:""},{id:uid(),type:"text",title:"Recipient",text:"Recipient Name\nCompany / Address"},{id:uid(),type:"text",title:"Subject",text:"RE: Business Communication"},{id:uid(),type:"text",title:"Letter",text:"Dear Sir/Madam,\n\nWrite your professional letter here.\n\nYours faithfully,"},{id:uid(),type:"signature",title:"Signature",text:"Welly|Administrator"}];

function loadCompany(){return {...defaults,...read(COMPANY_KEY,{})}}
function newDoc(type="profile"){return {id:uid(),name:type==="profile"?"Untitled Company Profile":"Untitled Letterhead",type,template:"modern",blocks:blocksFor(type),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}

export default function CompanyDocuments(){
 const [company,setCompany]=useState(loadCompany); const [docs,setDocs]=useState(()=>read(KEY,[])); const [activeId,setActiveId]=useState(()=>docs[0]?.id||null); const [type,setType]=useState("profile"); const [template,setTemplate]=useState("modern"); const [selected,setSelected]=useState(null); const [prompt,setPrompt]=useState(""); const [zoom,setZoom]=useState(70); const fileRef=useRef(null);
 const active=docs.find(d=>d.id===activeId)||null;
 const persist=(next)=>{setDocs(next);localStorage.setItem(KEY,JSON.stringify(next))};
 const updateDoc=(patch)=>{if(!active)return;persist(docs.map(d=>d.id===active.id?{...d,...patch,updatedAt:new Date().toISOString()}:d))};
 const updateBlocks=(blocks)=>updateDoc({blocks});
 const create=(t=type)=>{const d=newDoc(t);d.template=template;persist([...docs,d]);setActiveId(d.id);setType(t);setSelected(d.blocks[0].id)};
 const duplicate=()=>active&&(()=>{const d={...active,id:uid(),name:`${active.name} Copy`,blocks:active.blocks.map(b=>({...b,id:uid()})),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};persist([...docs,d]);setActiveId(d.id)})();
 const remove=()=>{if(active&&window.confirm("Delete this saved document?")){const n=docs.filter(d=>d.id!==active.id);persist(n);setActiveId(n[0]?.id||null)}};
 const saveCompany=(c)=>{setCompany(c);localStorage.setItem(COMPANY_KEY,JSON.stringify(c))};
 const generate=()=>{const p=prompt.trim();if(!p)return;const lower=p.toLowerCase();
  if(lower.includes("solmari air tech")||lower.includes("solmari")){
    const solmari={name:"SOLMARI AIR TECH AND SANITATION SOLUTIONS (PTY) LTD",tagline:"Cooling & Sanitation Solutions You Can Trust",registration:"Reg No. 2026/060291/07",address:"[Address to be added]",phone:"070 779 4667",email:"[Email to be added]",website:"",services:"HVAC, refrigeration, cooling, ventilation and portable sanitation solutions",primary:"#123B5D",secondary:"#18A7A1",font:"Arial"};
    saveCompany(solmari);
    const blocks=[
      {id:uid(),type:"hero",title:"COMPANY PROFILE",text:"Cooling & Sanitation Solutions You Can Trust"},
      {id:uid(),type:"text",title:"About Solmari",text:"SOLMARI AIR TECH AND SANITATION SOLUTIONS (PTY) LTD is a 100% Black-owned South African service provider delivering professional HVAC, refrigeration, cooling, ventilation and portable sanitation solutions. We serve residential, commercial, industrial, construction and event clients with a focus on affordability, energy efficiency, hygiene and dependable service."},
      {id:uid(),type:"columns",title:"Mission & Vision",text:"To provide affordable, energy-efficient cooling and hygienic sanitation solutions while delivering reliable workmanship and responsive customer service.|To become a leading one-stop provider of air-conditioning, refrigeration and sanitation solutions in South Africa."},
      {id:uid(),type:"services",title:"Air Conditioning & Refrigeration",text:"Supply & installation|Repairs & maintenance|Split & multi-split systems|Cassette & ducted systems|Under-ceiling & VRV/VRF systems|Window air conditioners|Cold & freezer rooms|Display fridges|Ventilation, extraction & ducting|Re-gassing, cleaning & servicing"},
      {id:uid(),type:"services",title:"Portable Sanitation Solutions",text:"Standard & flush portable toilets|VIP luxury toilet trailers|2-in-1 & 4-in-1 units with basins|Wheelchair-friendly facilities|Handwash basins|Portable showers|Urinal stands|Weekly cleaning & sanitising|Waste removal|Construction, events, weddings & funerals"},
      {id:uid(),type:"values",title:"Our Values",text:"Integrity|Professionalism|Reliability|Customer Satisfaction"},
      {id:uid(),type:"text",title:"Service Areas & Clients",text:"We provide services across Gauteng, North West and Limpopo, including Soshanguve, Tembisa, Newclare, Rustenburg, Pretoria and surrounding areas. Our target clients include homes, offices, schools, clinics, retail shops, construction sites, mines, events companies and municipalities."},
      {id:uid(),type:"text",title:"Why Choose Solmari",text:"Same-day service in selected service areas|Certified technicians and trade-tested personnel|24/7 emergency assistance|Affordable rates and free quotations|Warranty on workmanship|Compliance information can be provided where applicable"},
      {id:uid(),type:"text",title:"Contact Us",text:"Phone / WhatsApp: 070 779 4667\nEmail: [Email to be added]\nAddress: [Address to be added]\nOperating Hours: Monday–Saturday 07:00–19:00 | Sunday: Emergency Service"},
    ];
    const d={id:uid(),name:"SOLMARI Air Tech & Sanitation — Company Profile",type:"profile",template:"modern",blocks,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};
    persist([...docs,d]);setActiveId(d.id);setType("profile");setSelected(blocks[0].id);return;
  }
  if(!active){create("profile");return;} const blocks=active.blocks.map((b,i)=>i===0?{...b,text:p}:b);updateDoc({name:p.slice(0,45),blocks})};
 const addBlock=()=>{const b={id:uid(),type:"text",title:"New Section",text:"Click this section to edit it."};updateBlocks([...(active?.blocks||[]),b]);setSelected(b.id)};
 const move=(id,dir)=>{const a=[...(active?.blocks||[])],i=a.findIndex(x=>x.id===id),j=i+dir;if(i<0||j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];updateBlocks(a)};
 const updateBlock=(id,patch)=>updateBlocks(active.blocks.map(b=>b.id===id?{...b,...patch}:b));
 const removeBlock=id=>updateBlocks(active.blocks.filter(b=>b.id!==id));
 const selectedBlock=active?.blocks.find(b=>b.id===selected);
 const exportPDF=()=>window.print();
 const logoUpload=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>saveCompany({...company,logo:r.result});r.readAsDataURL(f)};
 const colors={primary:company.primary,secondary:company.secondary};
 return <div className="studio">
  <header className="studio-top no-print"><div><span className="studio-kicker">STYLZ IMS · DOCUMENT STUDIO</span><h1>Canva-style Business Designer</h1></div><div className="studio-actions"><button onClick={()=>create("profile")}><Plus size={16}/> New Profile</button><button onClick={()=>create("letter")}><Plus size={16}/> New Letterhead</button><button onClick={duplicate}><Copy size={16}/> Duplicate</button><button className="primary" onClick={exportPDF}><Download size={16}/> Download PDF</button></div></header>
  <div className="studio-layout no-print">
   <aside className="studio-sidebar">
    <div className="side-section"><strong>Saved Documents</strong>{docs.length===0&&<small>No saved documents yet.</small>}{docs.map(d=><button className={d.id===activeId?"doc-list active":"doc-list"} key={d.id} onClick={()=>{setActiveId(d.id);setType(d.type)}}><FileText size={15}/><span>{d.name}</span></button>)}</div>
    <div className="side-section"><strong>Templates</strong><button onClick={()=>{setType("profile");setTemplate("modern");create("profile")}}>Modern Profile</button><button onClick={()=>{setType("profile");setTemplate("corporate");create("profile")}}>Corporate Profile</button><button onClick={()=>{setType("profile");setTemplate("creative");create("profile")}}>Creative Profile</button><button onClick={()=>{setType("letter");setTemplate("classic");create("letter")}}>Classic Letterhead</button><button onClick={()=>{setType("letter");setTemplate("modern");create("letter")}}>Modern Letterhead</button><button onClick={()=>{setType("letter");setTemplate("bold");create("letter")}}>Bold Letterhead</button></div>
    {active&&<div className="side-section"><strong>Document</strong><input value={active.name} onChange={e=>updateDoc({name:e.target.value})}/><button onClick={addBlock}><Plus size={15}/> Add section</button><button onClick={remove} className="danger"><Trash2 size={15}/> Delete</button></div>}
   </aside>
   <main className="editor-area">
    <div className="editor-toolbar"><div className="tool-group"><button onClick={()=>setZoom(Math.max(40,zoom-10))}>−</button><span>{zoom}%</span><button onClick={()=>setZoom(Math.min(110,zoom+10))}>+</button></div><div className="tool-group"><button onClick={()=>fileRef.current?.click()}><Upload size={15}/> Logo</button><input ref={fileRef} type="file" accept="image/*" hidden onChange={logoUpload}/><label><Palette size={15}/> Primary <input type="color" value={company.primary} onChange={e=>saveCompany({...company,primary:e.target.value})}/></label><label>Secondary <input type="color" value={company.secondary} onChange={e=>saveCompany({...company,secondary:e.target.value})}/></label><label><Type size={15}/> Font <select value={company.font} onChange={e=>saveCompany({...company,font:e.target.value})}><option>Arial</option><option>Georgia</option><option>Verdana</option><option>Trebuchet MS</option><option>Times New Roman</option></select></label></div></div>
    <div className="canvas-scroll"><div className="canvas" style={{transform:`scale(${zoom/100})`}}>{active?<DocumentCanvas doc={active} company={company} colors={colors} selected={selected} setSelected={setSelected} updateBlock={updateBlock} move={move} removeBlock={removeBlock}/>:<div className="empty-canvas"><Wand2 size={38}/><h2>Create a document</h2><p>Choose a template or create a new company profile or letterhead.</p></div>}</div></div>
   </main>
   <aside className="properties no-print"><div className="property-title"><strong>Design & Content</strong><small>Selected element</small></div>{!active&&<p>Create a document to begin.</p>}{active&&<><div className="prompt-box"><Wand2 size={16}/><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Prompt this document..."/><button onClick={generate}>Generate</button></div><div className="prop-section"><strong>Company</strong>{["name","tagline","registration","address","phone","email","website","services"].map(k=><label key={k}>{k}<input value={company[k]||""} onChange={e=>saveCompany({...company,[k]:e.target.value})}/></label>)}</div>{selectedBlock&&<BlockEditor block={selectedBlock} update={p=>updateBlock(selectedBlock.id,p)}/>}</>}</aside>
  </div>
  {active&&<div className="mobile-save no-print"><button onClick={exportPDF}><Download size={16}/> Download PDF</button></div>}
 </div>
}

function BlockEditor({block,update}){return <div className="prop-section"><strong>Edit selected section</strong><label>Heading<input value={block.title||""} onChange={e=>update({title:e.target.value})}/></label><label>Content<textarea value={block.text||""} onChange={e=>update({text:e.target.value})}/></label><small>Use each line as a separate item in service/value sections.</small></div>}

function DocumentCanvas({doc,company,colors,selected,setSelected,updateBlock,move,removeBlock}){return <article className={`design-paper template-${doc.template} type-${doc.type}`} style={{fontFamily:company.font,"--primary":colors.primary,"--secondary":colors.secondary}}>{doc.blocks.map((b,i)=><section key={b.id} className={`design-block block-${b.type} ${selected===b.id?"selected":""}`} onClick={()=>setSelected(b.id)}><div className="block-handle no-print"><GripVertical size={14}/><button onClick={e=>{e.stopPropagation();move(b.id,-1)}}>↑</button><button onClick={e=>{e.stopPropagation();move(b.id,1)}}>↓</button><button onClick={e=>{e.stopPropagation();removeBlock(b.id)}}>×</button></div><BlockView block={b} company={company}/></section>)}</article>}
function BlockView({block,company}){if(block.type==="hero")return <><div className="hero-logo">{company.logo?<img src={company.logo}/>:<img src="/stylz_digital_logo.png"/>}</div><span>{block.title}</span><h2>{company.name}</h2><p>{company.tagline}</p></>;if(block.type==="letterHeader")return <><div className="letter-brand"><div className="hero-logo">{company.logo?<img src={company.logo}/>:<img src="/stylz_digital_logo.png"/>}</div><div><h2>{company.name}</h2><p>{company.tagline}</p></div><div className="contact">{company.phone}<br/>{company.email}<br/>{company.website}</div></div><div className="rule"/></>;if(block.type==="columns")return <><h3>{block.title}</h3><div className="columns">{block.text.split("|").map((x,i)=><div key={i}><h4>{i%2===0?"MISSION":"VISION"}</h4><p>{x}</p></div>)}</div></>;if(["services","values"].includes(block.type))return <><h3>{block.title}</h3><div className="chips">{block.text.split("|").map(x=><span key={x}>{x}</span>)}</div></>;if(block.type==="signature")return <div className="signature"><strong>{block.text.split("|")[0]}</strong><span>{block.text.split("|")[1]}</span></div>;return <><h3>{block.title}</h3>{block.text.split("\n").map((x,i)=><p key={i}>{x||"\u00a0"}</p>)}</>}
