import React,{useEffect,useRef,useState}from'react';
import{Download,Plus,Save,Copy,Trash2,Type,Image as ImageIcon,Square,AlignLeft,AlignCenter,AlignRight,ChevronLeft,ChevronRight,Layers,FileText,Undo2,Redo2,Grid3X3,Table2,QrCode,Palette,Library,ArrowUp,ArrowDown,Lock,Unlock,Scissors}from'lucide-react';import'./DocumentDesigner.css';
const STORE='stylz_ims_canvas_documents',TSTORE='stylz_ims_canvas_templates',uid=()=>Date.now()+Math.random(),load=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}};
const pg=()=>({id:uid(),background:'#fff',backgroundImage:'',elements:[]});const blank=(name='Untitled Design')=>({id:uid(),name,pages:[pg()],pageIndex:0,updatedAt:new Date().toISOString()});
const el=(type)=>({id:uid(),type,x:80,y:80,w:type==='text'?360:220,h:type==='text'?70:150,text:type==='text'?'Double-click to edit':'',fontSize:28,fontWeight:600,align:'left',fill:type==='shape'?'#174ea6':'transparent',color:'#172033',src:'',radius:0,locked:false,opacity:1,objectPosition:'center',cropZoom:1,cols:3,rows:3,url:'https://stylzdigital.co.za'});
const clone=d=>JSON.parse(JSON.stringify(d));
const fonts=['Arial','Georgia','Verdana','Trebuchet MS','Times New Roman','Courier New','Impact','Montserrat','Poppins','Roboto','Open Sans','Lato'];
const marketplace=[{name:'STYLZ Corporate Profile',cat:'Company Profiles',accent:'#174ea6'},{name:'Modern Business Letterhead',cat:'Letterheads',accent:'#e31b23'},{name:'Construction Company Profile',cat:'Company Profiles',accent:'#222'},{name:'Professional Quotation',cat:'Business',accent:'#174ea6'},{name:'Creative Agency Profile',cat:'Company Profiles',accent:'#e31b23'},{name:'Invoice / Statement',cat:'Business',accent:'#174ea6'}];
export default function DocumentDesigner(){
 const[docs,setDocs]=useState(()=>load(STORE)),[templates,setTemplates]=useState(()=>load(TSTORE)),[doc,setDoc]=useState(null),[sel,setSel]=useState(null),[zoom,setZoom]=useState(.75),[drag,setDrag]=useState(null),[resize,setResize]=useState(null),[grid,setGrid]=useState(true),[guides,setGuides]=useState(true),[tab,setTab]=useState('elements'),[history,setHistory]=useState([]),[future,setFuture]=useState([]),file=useRef();
 const page=doc?.pages[doc.pageIndex],selected=page?.elements.find(x=>x.id===sel);const snap=v=>grid?Math.round(v/10)*10:v;
 const commit=(next)=>{if(!doc)return;setHistory(h=>[...h.slice(-29),clone(doc)]);setFuture([]);setDoc({...next,updatedAt:new Date().toISOString()})};
 const update=patch=>commit({...doc,...patch});const pageUpdate=p=>commit({...doc,pages:doc.pages.map((x,i)=>i===doc.pageIndex?p:x)});const updateEl=patch=>pageUpdate({...page,elements:page.elements.map(x=>x.id===sel?{...x,...patch}:x)});
 const add=(type)=>{const x=el(type);if(type==='table')x.text='Item|Qty|Price\nProduct|1|R0\nService|1|R0';if(type==='qr')x.w=x.h=150;pageUpdate({...page,elements:[...page.elements,x]});setSel(x.id)};
 const newDoc=()=>{const d=blank();setDoc(d);setSel(null);setHistory([]);setFuture([])};const save=()=>{if(!doc)return;const n=docs.some(x=>x.id===doc.id)?docs.map(x=>x.id===doc.id?doc:x):[...docs,doc];setDocs(n);localStorage.setItem(STORE,JSON.stringify(n))};
 const duplicate=()=>{if(!selected)return;const x={...selected,id:uid(),x:selected.x+20,y:selected.y+20};pageUpdate({...page,elements:[...page.elements,x]});setSel(x.id)};const remove=()=>selected&&!selected.locked&&pageUpdate({...page,elements:page.elements.filter(x=>x.id!==sel)});
 const addPage=()=>update({pages:[...doc.pages,pg()],pageIndex:doc.pages.length});const delPage=()=>doc.pages.length>1&&update({pages:doc.pages.filter((_,i)=>i!==doc.pageIndex),pageIndex:Math.max(0,doc.pageIndex-1)});
 const saveTemplate=()=>{if(!doc)return;const t={...clone(doc),id:uid(),name:`${doc.name} Template`,marketplace:true};const n=[...templates,t];setTemplates(n);localStorage.setItem(TSTORE,JSON.stringify(n))};const useTemplate=t=>{const d={...clone(t),id:uid(),name:`${t.name} Copy`,pages:t.pages.map(p=>({...p,id:uid(),elements:p.elements.map(x=>({...x,id:uid()}))}))};setDoc(d);setSel(null)};
 const upload=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const x=el('image');x.src=r.result;x.w=300;x.h=200;pageUpdate({...page,elements:[...page.elements,x]});setSel(x.id)};r.readAsDataURL(f)};
 const undo=()=>{if(!history.length)return;const h=history[history.length-1];setFuture(f=>[clone(doc),...f.slice(0,29)]);setHistory(history.slice(0,-1));setDoc(h)};const redo=()=>{if(!future.length)return;const f=future[0];setHistory(h=>[...h.slice(-29),clone(doc)]);setFuture(future.slice(1));setDoc(f)};
 useEffect(()=>{const key=e=>{const cmd=e.ctrlKey||e.metaKey;if(cmd&&e.key==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if(cmd&&e.key==='y'){e.preventDefault();redo()}else if(cmd&&e.key==='s'){e.preventDefault();save()}else if(cmd&&e.key==='c'&&selected){e.preventDefault();localStorage.setItem('stylz_canvas_clip',JSON.stringify(selected))}else if(cmd&&e.key==='v'){const c=load('stylz_canvas_clip');if(c?.id&&page){const x={...c,id:uid(),x:c.x+20,y:c.y+20};pageUpdate({...page,elements:[...page.elements,x]});setSel(x.id)}}else if((e.key==='Delete'||e.key==='Backspace')&&selected&&!selected.locked)remove();else if(selected&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const d=e.shiftKey?10:1;updateEl({x:snap(selected.x+(e.key==='ArrowLeft'?-d:e.key==='ArrowRight'?d:0)),y:snap(selected.y+(e.key==='ArrowUp'?-d:e.key==='ArrowDown'?d:0))})}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[doc,selected,history,future]);
 useEffect(()=>{const move=e=>{if(drag&&page){const dx=(e.clientX-drag.sx)/zoom,dy=(e.clientY-drag.sy)/zoom;const x=snap(Math.max(0,drag.ox+dx)),y=snap(Math.max(0,drag.oy+dy));setDoc(d=>({...d,pages:d.pages.map((p,i)=>i===d.pageIndex?{...p,elements:p.elements.map(q=>q.id===drag.id?{...q,x,y}:q)}:p)}))}if(resize&&page){const dx=(e.clientX-resize.sx)/zoom,dy=(e.clientY-resize.sy)/zoom;setDoc(d=>({...d,pages:d.pages.map((p,i)=>i===d.pageIndex?{...p,elements:p.elements.map(q=>q.id===resize.id?{...q,w:Math.max(30,snap(resize.ow+dx)),h:Math.max(20,snap(resize.oh+dy))}:q)}:p)}))}};const up=()=>{if(drag||resize){setHistory(h=>[...h.slice(-29),clone(doc)]);setFuture([])}setDrag(null);setResize(null)};window.addEventListener('mousemove',move);window.addEventListener('mouseup',up);return()=>{window.removeEventListener('mousemove',move);window.removeEventListener('mouseup',up)}},[drag,resize,zoom,page,doc]);
 const startDrag=(e,id)=>{e.stopPropagation();const x=page.elements.find(q=>q.id===id);if(!x||x.locked)return;setSel(id);if(!e.target.closest('.resize-handle'))setDrag({id,sx:e.clientX,sy:e.clientY,ox:x.x,oy:x.y})};const startResize=(e)=>{e.stopPropagation();setResize({id:selected.id,sx:e.clientX,sy:e.clientY,ow:selected.w,oh:selected.h})};
 const addTable=()=>add('table'),addQR=()=>add('qr');const setBg=(v)=>pageUpdate({...page,background:v});const pageBg=page?.background||'#fff';
 return <div className="dd"><header className="dd-head no-print"><div><span>STYLZ IMS · DOCUMENT STUDIO</span><h1>{doc?.name||'Canva-style Business Designer'}</h1></div><div className="dd-actions"><button onClick={newDoc}><Plus size={15}/>New</button><button onClick={undo} disabled={!history.length}><Undo2 size={15}/></button><button onClick={redo} disabled={!future.length}><Redo2 size={15}/></button><button onClick={save}><Save size={15}/>Save</button><button onClick={saveTemplate}><Copy size={15}/>Save Template</button><button onClick={()=>window.print()} className="primary"><Download size={15}/>PDF</button></div></header>
 <div className="dd-body no-print"><aside className="dd-left"><div className="tabs"><button className={tab==='elements'?'on':''} onClick={()=>setTab('elements')}>Elements</button><button className={tab==='layers'?'on':''} onClick={()=>setTab('layers')}><Layers size={14}/>Layers</button><button className={tab==='library'?'on':''} onClick={()=>setTab('library')}><Library size={14}/>Library</button></div>{tab==='elements'&&<><strong>ADD</strong><button onClick={()=>add('text')}><Type/>Text</button><button onClick={()=>add('shape')}><Square/>Shape</button><button onClick={()=>file.current?.click()}><ImageIcon/>Image</button><button onClick={addTable}><Table2/>Table</button><button onClick={addQR}><QrCode/>QR Code</button><input ref={file} type="file" accept="image/*" hidden onChange={upload}/><hr/><strong>VIEW</strong><button onClick={()=>setGrid(!grid)}><Grid3X3/>Grid {grid?'On':'Off'}</button><button onClick={()=>setGuides(!guides)}>Guides {guides?'On':'Off'}</button></>}{tab==='layers'&&<>{page?.elements.slice().reverse().map((x,i)=><button className={x.id===sel?'active':''} key={x.id} onClick={()=>setSel(x.id)}><Layers size={14}/>{x.type} {i+1}{x.locked?' 🔒':''}</button>)}</>}{tab==='library'&&<TemplateLibrary templates={templates} marketplace={marketplace} useTemplate={useTemplate}/>}</aside>
 <main className="dd-main"><div className="dd-toolbar"><button onClick={()=>setZoom(Math.max(.5,zoom-.1))}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(Math.min(1.3,zoom+.1))}>+</button>{selected&&<><button onClick={duplicate}><Copy size={14}/></button><button onClick={remove}><Trash2 size={14}/></button><button onClick={()=>updateEl({locked:!selected.locked})}>{selected.locked?<Unlock size={14}/>:<Lock size={14}/>}</button>{selected.type==='text'&&<><select value={selected.fontFamily||'Arial'} onChange={e=>updateEl({fontFamily:e.target.value})}>{fonts.map(f=><option key={f}>{f}</option>)}</select><input type="number" value={selected.fontSize} onChange={e=>updateEl({fontSize:Number(e.target.value)})}/><button onClick={()=>updateEl({fontWeight:selected.fontWeight>600?400:800})}>B</button><button onClick={()=>updateEl({align:'left'})}><AlignLeft/></button><button onClick={()=>updateEl({align:'center'})}><AlignCenter/></button><button onClick={()=>updateEl({align:'right'})}><AlignRight/></button><input type="color" value={selected.color} onChange={e=>updateEl({color:e.target.value})}/></>}</>}</div>
 <div className="canvas-area">{doc?<div className="a4" style={{transform:`scale(${zoom})`,background:pageBg,backgroundImage:page?.backgroundImage?`url(${page.backgroundImage})`:undefined}} onMouseDown={()=>setSel(null)}>{guides&&<div className="guide-v"/>}{guides&&<div className="guide-h"/>}{grid&&<div className="grid-overlay"/ >}{page?.elements.map(x=><CanvasElement key={x.id} x={x} selected={sel===x.id} onDown={startDrag} onResize={startResize} onChange={p=>{setSel(x.id);updateEl(p)}}/>)}</div>:<div className="empty"><h2>Build anything for STYLZ</h2><p>Profiles, letterheads, brochures, quotations, flyers and business documents.</p><button onClick={newDoc}>Create Document</button></div>}</div>
 <div className="pages-bar">{doc&&doc.pages.map((p,i)=><button className={i===doc.pageIndex?'pg-on':''} key={p.id} onClick={()=>update({pageIndex:i})}>{i+1}</button>)}<button onClick={addPage}><Plus/>Page</button><button onClick={delPage} disabled={!doc||doc.pages.length===1}><Trash2/></button><label><Palette/>BG<input type="color" value={pageBg} onChange={e=>setBg(e.target.value)}/></label><span className="shortcuts">Ctrl+Z Undo · Ctrl+Y Redo · Ctrl+C/V Copy · Arrows Move · Delete Remove</span></div></main>
 <aside className="dd-right"><strong>Properties</strong>{selected?<Properties x={selected} update={updateEl}/>:<p>Select an element. Use the Layers tab to manage stacking order.</p>}</aside></div></div>}
function Properties({x,update}){return <div className="props"><label>X<input type="number" value={Math.round(x.x)} onChange={e=>update({x:Number(e.target.value)})}/></label><label>Y<input type="number" value={Math.round(x.y)} onChange={e=>update({y:Number(e.target.value)})}/></label><label>Width<input type="number" value={Math.round(x.w)} onChange={e=>update({w:Number(e.target.value)})}/></label><label>Height<input type="number" value={Math.round(x.h)} onChange={e=>update({h:Number(e.target.value)})}/></label>{x.type==='text'&&<label>Text<textarea value={x.text} onChange={e=>update({text:e.target.value})}/></label>}{x.type==='image'&&<><label>Crop Zoom<input type="range" min="1" max="2" step=".05" value={x.cropZoom||1} onChange={e=>update({cropZoom:Number(e.target.value)})}/></label><label>Crop Position<select value={x.objectPosition||'center'} onChange={e=>update({objectPosition:e.target.value})}><option>center</option><option>top</option><option>bottom</option><option>left</option><option>right</option></select></label></>}{['shape','text'].includes(x.type)&&<label>Fill<input type="color" value={x.fill==='transparent'?'#ffffff':x.fill} onChange={e=>update({fill:e.target.value})}/></label>}{x.type==='qr'&&<label>QR URL / Text<input value={x.url} onChange={e=>update({url:e.target.value})}/></label>}</div>}
function CanvasElement({x,selected,onDown,onResize,onChange}){const style={left:x.x,top:x.y,width:x.w,height:x.h,color:x.color,background:x.fill,borderRadius:x.radius,fontSize:x.fontSize,fontWeight:x.fontWeight,textAlign:x.align,fontFamily:x.fontFamily||'Arial',opacity:x.opacity};return <div className={`dd-el el-${x.type} ${selected?'selected':''}`} style={style} onMouseDown={e=>onDown(e,x.id)}>{x.type==='text'&&<div contentEditable suppressContentEditableWarning onBlur={e=>onChange({text:e.currentTarget.innerText})}>{x.text}</div>}{x.type==='image'&&x.src&&<img src={x.src} style={{objectPosition:x.objectPosition||'center',transform:`scale(${x.cropZoom||1})`}} draggable="false"/>}{x.type==='shape'&&null}{x.type==='table'&&<TableBlock text={x.text}/>} {x.type==='qr'&&<img src={`https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(x.url||'')}`} draggable="false"/>}{selected&&<div className="resize-handle" onMouseDown={onResize}/>}</div>}
function TableBlock({text}){const rows=(text||'').split('\n').map(r=>r.split('|'));return <table><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j} className={i===0?'th':''}>{c}</td>)}</tr>)}</tbody></table>}
function TemplateLibrary({templates,marketplace,useTemplate}){return <div className="library">{marketplace.map((m,i)=><button key={i} onClick={()=>useTemplate({id:uid(),name:m.name,pages:[{id:uid(),background:'#fff',elements:[{...el('shape'),id:uid(),x:0,y:0,w:794,h:180,fill:m.accent},{...el('text'),id:uid(),x:70,y:65,text:m.name,fontSize:34,color:'#fff',fill:'transparent'}]}]})}><span style={{background:m.accent}}/>{m.name}<small>{m.cat}</small></button>)}<hr/><strong>My Templates</strong>{templates.map(t=><button key={t.id} onClick={()=>useTemplate(t)}><Layers/>{t.name}</button>)}</div>}
