import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Download,Plus,Save,Copy,Trash2,Type,Image as ImageIcon,Square,AlignLeft,AlignCenter,AlignRight,ChevronLeft,ChevronRight,Layers,FileText} from 'lucide-react';
import './DocumentDesigner.css';

const STORE='stylz_ims_canvas_documents'; const TSTORE='stylz_ims_canvas_templates';
const uid=()=>Date.now()+Math.random(); const load=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}};
const page=()=>({id:uid(),elements:[]});
const blankDoc=(name='Untitled Design')=>({id:uid(),name,pages:[page()],pageIndex:0,updatedAt:new Date().toISOString()});
const element=(type)=>({id:uid(),type,x:70,y:70,w:type==='text'?360:220,h:type==='text'?70:180,text:type==='text'?'Double-click to edit':type==='shape'?'':'' ,fontSize:28,fontWeight:600,align:'left',fill:'#174ea6',color:'#172033',src:'',radius:0});

export default function DocumentDesigner(){
 const [docs,setDocs]=useState(()=>load(STORE)),[templates,setTemplates]=useState(()=>load(TSTORE)); const [activeId,setActiveId]=useState(null); const [doc,setDoc]=useState(null); const [selected,setSelected]=useState(null); const [zoom,setZoom]=useState(.8); const [drag,setDrag]=useState(null); const [resize,setResize]=useState(null); const file=useRef();
 const activePage=doc?.pages[doc.pageIndex]; const sel=activePage?.elements.find(e=>e.id===selected);
 const persistDocs=(next)=>{setDocs(next);localStorage.setItem(STORE,JSON.stringify(next))};
 const save=(d=doc)=>{if(!d)return;const n=docs.some(x=>x.id===d.id)?docs.map(x=>x.id===d.id?d:x):[...docs,d];persistDocs(n);setDoc({...d,updatedAt:new Date().toISOString()})};
 const newDoc=()=>{const d=blankDoc();setDoc(d);setActiveId(d.id);setSelected(null);};
 const update=(patch)=>{const d={...doc,...patch,updatedAt:new Date().toISOString()};setDoc(d)};
 const updatePage=(p)=>update({pages:doc.pages.map((x,i)=>i===doc.pageIndex?p:x)});
 const add=(type)=>{const e=element(type);updatePage({...activePage,elements:[...activePage.elements,e]});setSelected(e.id)};
 const updateEl=(patch)=>updatePage({...activePage,elements:activePage.elements.map(e=>e.id===selected?{...e,...patch}:e)});
 const remove=()=>updatePage({...activePage,elements:activePage.elements.filter(e=>e.id!==selected)});
 const duplicate=()=>{if(!sel)return;const e={...sel,id:uid(),x:sel.x+20,y:sel.y+20};updatePage({...activePage,elements:[...activePage.elements,e]});setSelected(e.id)};
 const addPage=()=>{const p=page();update({pages:[...doc.pages,p],pageIndex:doc.pages.length});setSelected(null)};
 const delPage=()=>{if(doc.pages.length===1)return;const pages=doc.pages.filter((_,i)=>i!==doc.pageIndex);update({pages,pageIndex:Math.max(0,doc.pageIndex-1)});setSelected(null)};
 const saveTemplate=()=>{if(!doc)return;const t={...doc,id:uid(),name:`${doc.name} Template`};const n=[...templates,t];setTemplates(n);localStorage.setItem(TSTORE,JSON.stringify(n))};
 const useTemplate=t=>{const d={...t,id:uid(),name:`${t.name} Copy`,pages:t.pages.map(p=>({...p,id:uid(),elements:p.elements.map(e=>({...e,id:uid()}))}))};setDoc(d);setActiveId(d.id);setSelected(null)};
 const upload=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const x=element('image');x.src=r.result;x.w=280;x.h=180;updatePage({...activePage,elements:[...activePage.elements,x]});setSelected(x.id)};r.readAsDataURL(f)};
 const startDrag=(e,id)=>{if(e.target.closest('.resize-handle'))return;e.stopPropagation();const el=activePage.elements.find(x=>x.id===id);setSelected(id);setDrag({id,sx:e.clientX,sy:e.clientY,ox:el.x,oy:el.y})};
 useEffect(()=>{const move=e=>{if(drag){const dx=(e.clientX-drag.sx)/zoom,dy=(e.clientY-drag.sy)/zoom;updatePage({...activePage,elements:activePage.elements.map(x=>x.id===drag.id?{...x,x:Math.max(0,drag.ox+dx),y:Math.max(0,drag.oy+dy)}:x)})}if(resize){const dx=(e.clientX-resize.sx)/zoom,dy=(e.clientY-resize.sy)/zoom;updatePage({...activePage,elements:activePage.elements.map(x=>x.id===resize.id?{...x,w:Math.max(30,resize.ow+dx),h:Math.max(20,resize.oh+dy)}:x)})}};const up=()=>{setDrag(null);setResize(null)};window.addEventListener('mousemove',move);window.addEventListener('mouseup',up);return()=>{window.removeEventListener('mousemove',move);window.removeEventListener('mouseup',up)}},[drag,resize,activePage,zoom]);
 const pagesCount=doc?.pages.length||0;
 return <div className="dd"><header className="dd-head no-print"><div><span>STYLZ IMS · CANVAS DESIGNER</span><h1>{doc?.name||'Document Designer'}</h1></div><div className="dd-actions"><button onClick={newDoc}><Plus size={16}/> New</button><button onClick={()=>doc&&save()}><Save size={16}/> Save</button><button onClick={()=>doc&&saveTemplate()}><Copy size={16}/> Save Template</button><button onClick={()=>window.print()} className="primary"><Download size={16}/> PDF</button></div></header>
 <div className="dd-body no-print"><aside className="dd-left"><strong>Documents</strong>{docs.map(d=><button className={activeId===d.id?'active':''} onClick={()=>{setDoc(d);setActiveId(d.id);setSelected(null)}} key={d.id}><FileText size={14}/>{d.name}</button>)}<hr/><strong>Templates</strong>{templates.map(t=><button onClick={()=>useTemplate(t)} key={t.id}><Layers size={14}/>{t.name}</button>)}<hr/><button onClick={()=>add('text')}><Type size={15}/> Text</button><button onClick={()=>add('shape')}><Square size={15}/> Shape</button><button onClick={()=>file.current?.click()}><ImageIcon size={15}/> Image</button><input ref={file} type="file" accept="image/*" hidden onChange={upload}/></aside>
 <main className="dd-main"><div className="dd-toolbar"><button onClick={()=>setZoom(Math.max(.5,zoom-.1))}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(Math.min(1.3,zoom+.1))}>+</button>{sel&&<><button onClick={duplicate}><Copy size={14}/> Duplicate</button><button onClick={remove}><Trash2 size={14}/></button>{sel.type==='text'&&<><input className="num" type="number" value={sel.fontSize} onChange={e=>updateEl({fontSize:Number(e.target.value)})}/><button className={sel.fontWeight>600?'active':''} onClick={()=>updateEl({fontWeight:sel.fontWeight>600?400:800})}>B</button><button onClick={()=>updateEl({align:'left'})}><AlignLeft size={14}/></button><button onClick={()=>updateEl({align:'center'})}><AlignCenter size={14}/></button><button onClick={()=>updateEl({align:'right'})}><AlignRight size={14}/></button><input type="color" value={sel.color} onChange={e=>updateEl({color:e.target.value})}/></>}</>}</div>
 <div className="canvas-area">{doc?<div className="a4" style={{transform:`scale(${zoom})`}} onMouseDown={()=>setSelected(null)}>{activePage?.elements.map(e=><Element key={e.id} e={e} selected={selected===e.id} onDown={startDrag} onResize={(ev)=>{ev.stopPropagation();setResize({id:e.id,sx:ev.clientX,sy:ev.clientY,ow:e.w,oh:e.h})}} onChange={p=>{setSelected(e.id);updatePage({...activePage,elements:activePage.elements.map(x=>x.id===e.id?{...x,...p}:x)})}}/> )}</div>:<div className="empty"><h2>Start designing</h2><p>Create a document, then drag text, images and shapes anywhere on the A4 canvas.</p><button onClick={newDoc}>Create Document</button></div>}</div>
 <div className="pages-bar"><button disabled={!doc||doc.pageIndex===0} onClick={()=>update({pageIndex:doc.pageIndex-1})}><ChevronLeft/></button><span>{doc?`Page ${doc.pageIndex+1} of ${pagesCount}`:'No document'}</span><button disabled={!doc||doc.pageIndex===pagesCount-1} onClick={()=>update({pageIndex:doc.pageIndex+1})}><ChevronRight/></button><button onClick={addPage}><Plus/> Page</button><button onClick={delPage} disabled={!doc||pagesCount===1}><Trash2/> Page</button></div></main>
 <aside className="dd-right"><strong>Properties</strong>{sel?<><label>X<input type="number" value={Math.round(sel.x)} onChange={e=>updateEl({x:Number(e.target.value)})}/></label><label>Y<input type="number" value={Math.round(sel.y)} onChange={e=>updateEl({y:Number(e.target.value)})}/></label><label>Width<input type="number" value={Math.round(sel.w)} onChange={e=>updateEl({w:Number(e.target.value)})}/></label><label>Height<input type="number" value={Math.round(sel.h)} onChange={e=>updateEl({h:Number(e.target.value)})}/></label>{sel.type==='text'&&<label>Text<textarea value={sel.text} onChange={e=>updateEl({text:e.target.value})}/></label>}{sel.type==='shape'&&<label>Fill<input type="color" value={sel.fill} onChange={e=>updateEl({fill:e.target.value})}/></label>}{sel.type==='text'&&<label>Background<input type="color" value={sel.fill} onChange={e=>updateEl({fill:e.target.value})}/></label>}</>:<p>Select an object to edit its position, size and styling.</p>}</aside></div></div>}

function Element({e,selected,onDown,onResize,onChange}){const style={left:e.x,top:e.y,width:e.w,height:e.h,color:e.color,background:e.fill,borderRadius:e.radius,fontSize:e.fontSize,fontWeight:e.fontWeight,textAlign:e.align};return <div className={`dd-el ${selected?'selected':''} el-${e.type}`} style={style} onMouseDown={ev=>onDown(ev,e.id)}>{e.type==='text'&&<div contentEditable suppressContentEditableWarning onBlur={ev=>onChange({text:ev.currentTarget.innerText})}>{e.text}</div>}{e.type==='image'&&e.src&&<img src={e.src} draggable="false"/>}{e.type==='shape'&&null}{selected&&<div className="resize-handle" onMouseDown={onResize}/>}</div>}
