import React, { useEffect, useMemo, useState } from "react";
import { LayoutDashboard, Users, FileText, ClipboardList, Printer, Receipt, CreditCard, Package, Wallet, UserCog, BarChart3, Settings, Plus, ArrowUpRight, CheckCircle2, Palette } from "lucide-react";
import Customers from "./pages/Customers";
import Quotes from "./pages/Quotes";
import Invoices from "./pages/Invoices";
import Orders from "./pages/Orders";
import Products from "./pages/Products";
import Management from "./pages/Management";
import DocumentDesigner from "./pages/DocumentDesigner";
import "./App.css";
const menuItems=[{label:"Dashboard",icon:LayoutDashboard},{label:"Customers",icon:Users},{label:"Quotations",icon:FileText},{label:"Orders / Jobs",icon:ClipboardList},{label:"Production",icon:Printer},{label:"Document Designer",icon:Palette},{label:"Invoices",icon:Receipt},{label:"Payments",icon:CreditCard},{label:"Inventory",icon:Package},{label:"Products & Prices",icon:Package},{label:"Expenses",icon:Wallet},{label:"Staff",icon:UserCog},{label:"Reports",icon:BarChart3},{label:"Settings",icon:Settings}];
const INVOICE_FROM_ORDER_KEY="stylz_ims_invoice_from_order";
function App(){const[activePage,setActivePage]=useState("Dashboard"),[openNewOrder,setOpenNewOrder]=useState(false);const handleCreateInvoiceFromOrder=order=>{try{localStorage.setItem(INVOICE_FROM_ORDER_KEY,JSON.stringify(order))}catch(e){alert("Could not prepare this order for invoicing.");return}setActivePage("Invoices")};return <div className="app-shell"><Sidebar activePage={activePage} onNavigate={setActivePage}/><main className="main-content">{activePage==="Dashboard"&&<Dashboard onNewOrder={()=>setOpenNewOrder(true)} onNavigate={setActivePage}/>} {activePage==="Customers"&&<Customers/>}{activePage==="Quotations"&&<Quotes/>}{activePage==="Invoices"&&<Invoices/>}<div style={{display:activePage==="Orders / Jobs"?"block":"none"}}><Orders openNewOrder={openNewOrder} setOpenNewOrder={setOpenNewOrder} isPageVisible={activePage==="Orders / Jobs"} onCreateInvoice={handleCreateInvoiceFromOrder}/></div>{activePage==="Products & Prices"&&<Products/>}{["Production","Payments","Inventory","Expenses","Staff"].includes(activePage)&&<Management module={activePage}/>} {activePage==="Document Designer"&&<DocumentDesigner/>}{activePage==="Reports"&&<Reports/>}{activePage==="Settings"&&<SettingsPage/>}</main></div>}
function Sidebar({activePage,onNavigate}){return <aside className="sidebar"><div className="brand"><img src="/stylz_digital_logo.png" alt="STYLZ Digital Solutions" className="sidebar-logo"/><div className="brand-text"><strong>STYLZ</strong><span>DIGITAL SOLUTIONS</span></div></div><nav className="sidebar-nav">{menuItems.map(item=>{const Icon=item.icon;return <button key={item.label} type="button" className={activePage===item.label?"nav-item active":"nav-item"} onClick={()=>onNavigate(item.label)}><Icon size={19}/><span>{item.label}</span></button>})}</nav></aside>}
function Dashboard(){return <div className="page"><div className="page-header"><div><h1>Dashboard</h1><p>Welcome to STYLZ Digital Solutions.</p></div></div><div className="stats-grid"><div className="stat-card"><div className="stat-info"><span>Document Designer</span><strong>Ready</strong><small>Create profiles, letterheads and marketing documents.</small></div></div></div></div>}
function Reports(){return <div className="page"><div className="page-header"><div><h1>Reports</h1><p>Business reports and performance overview.</p></div></div></div>}
function SettingsPage(){return <div className="page"><div className="page-header"><div><h1>Settings</h1><p>Manage STYLZ IMS settings.</p></div></div></div>}
export default App;
